/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIlearn_JNIMath */

#ifndef _Included_JNIlearn_JNIMath
#define _Included_JNIlearn_JNIMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIlearn_JNIMath
 * Method:    jiecheng
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIlearn_JNIMath_jiecheng
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
