package ${packageName}

import org.junit.Test
import spock.lang.Specification

${BizClassNameImports}

/**
 * AutoGenerated BY AutoUTGenerator.groovy
 */
class ${ClassName}AutoTest extends Specification {

   def $inst = new ${ClassName}()

   ${AllTestMethods}

}